### ISSUE TITLE
Revert to standard/default port

### ISSUE THREAD

**Issue by nickerso** [dewancse/model-discovery-tool#4]
We should revert the nginx config to the default port now that we are live and remove the need to use port 8181 in the URL we want to distribute and get people to use.

I think simply removing this line from `nginx.conf` should work:
```
listen       8181;
```
along with corresponding updates in the README.

**Comment by dewancse** [comment]
I have removed the port 8181 fro the nginx.conf and it works fine. Also, mentioned the new IP in the README.
