### ISSUE TITLE
Installing MDT

### ISSUE THREAD

**Issue by agarny** [dewancse/model-discovery-tool#8]
Hi @dewancse, I just followed your instructions to get MDT running, but I think a step is missing. In other words, I think your steps should be:

```
git clone https://github.com/dewancse/model-discovery-tool
cd model-discovery-tool
docker build -f Dockerfile -t unique-name/mdt-nginx .
docker run -p 49160:80 -d unique-name/mdt-nginx
```

**Comment by dewancse** [comment]
Hi @agarny - thank you for your instructions. I have now updated the installation section.
