### ISSUE TITLE
Generate an official release of MDT

### ISSUE THREAD

**Issue by agarny** [dewancse/model-discovery-tool#9]
Hi @dewancse, since you have recently published your paper on MDT, it would be good to have an official release for it, and maybe update the installation information accordingly (see issue #8).

**Comment by dewancse** [comment]
Hi @agarny - thanks very much for helping me to improve the MDT. I have now updated the installation information that you suggested on #8, as well as released v1.0.

**Comment by agarny** [comment]
Thanks @dewancse. Feel free to close this issue, as well as issues #7 and #8.
